# Generated by Django 5.0.7 on 2024-08-04 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_alter_task_options_remove_workfield_task_and_more'),
        ('users', '0003_user_work_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_field',
        ),
        migrations.CreateModel(
            name='WorkFieldUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.workfield', verbose_name='Поле')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='work_field',
            field=models.ManyToManyField(through='users.WorkFieldUser', to='tasks_app.workfield', verbose_name='Поле'),
        ),
    ]
