# Generated by Django 5.0.7 on 2024-08-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='task',
            name='piority_status',
            field=models.SmallIntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий'), (3, 'Критический')], default=0),
        ),
        migrations.AlterField(
            model_name='workfield',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
