# Generated by Django 5.0.7 on 2024-08-07 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_alter_workfield_tasks_alter_workfieldtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfieldtask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task', verbose_name='Задача'),
        ),
    ]
