# Generated by Django 5.0.7 on 2024-08-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_task_content_task_piority_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='workfield',
            name='task',
        ),
        migrations.CreateModel(
            name='WorkFieldTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task', verbose_name='Задача')),
                ('work_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app.workfield', verbose_name='Поле')),
            ],
        ),
        migrations.AddField(
            model_name='workfield',
            name='tasks',
            field=models.ManyToManyField(through='tasks_app.WorkFieldTask', to='tasks_app.task', verbose_name='Задачи'),
        ),
    ]
