# Generated by Django 5.0.7 on 2024-08-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_alter_workfieldtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workfield',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='workfieldtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='workfieldtask',
            name='work_field',
        ),
        migrations.AddField(
            model_name='workfieldtask',
            name='task',
            field=models.ManyToManyField(blank=True, to='tasks_app.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='workfieldtask',
            name='work_field',
            field=models.ManyToManyField(to='tasks_app.workfield', verbose_name='Поле'),
        ),
    ]
