# Generated by Django 5.0.7 on 2024-08-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0005_workfield_tasks_remove_workfieldtask_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfieldtask',
            name='work_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app.workfield', verbose_name='Поле'),
        ),
    ]
